openapi: 3.0.0
info:
  title: Quit Smoking API
  version: 1.0.0
paths:
  /hello:
    get:
      summary: Returns a hello message
      operationId: getHello
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
